name:                flowerFighting
version:             0.1.0.0
github:              "minchurl/flowerFighting"
license:             BSD3
author:              "Minchurl Shin"
maintainer:          "minchurl@kaist.ac.kr"
copyright:           "2021 Minchurl Shin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/flowerFighting#readme>

dependencies:
- base >= 4.7 && < 5
- tasty >= 1.4
- tasty-hunit >= 0.10
- tasty-smallcheck >= 0.8
- tasty-quickcheck >= 0.10
- containers
- generic-random
- mtl
- transformers
- random

library:
  source-dirs: src

executables:
  flowerFighting-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flowerFighting

tests:
  flowerFighting-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flowerFighting
